services:
  database:
    image: postgres:15
    container_name: goomer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: goomer_menu_api
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: goomer_api
    restart: always
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: goomer_menu_api
      DATABASE_URL: postgresql://postgres:123456@database:5432/goomer_menu_api
    ports:
      - "3002:3000"
    depends_on:
      - database

volumes:
  postgres_data:
